let courseData = 
[{"key":"B00OSTKZWM1",
	"name":"Learn React JS",
	"Instructor":"Jammal Mia",
	"img":"https://i.ibb.co/8M9vLH1/react.png",	
	"price":9.99},
	{"key":"B00OSTKZWM2",
	"name":"Learn Angular JS",
	"Instructor":"MRS Jhon",
	"img":"https://i.ibb.co/k43chcf/Angular-JS.png",	
	"price":12.99},
	{"key":"B00OSTKZWM3",
	"name":"Complete JavaScript",
	"Instructor":"Jammal Mia",
	"img":"https://i.ibb.co/ysw5Jmh/javascript.jpg",	
	"price":11.99},
	{"key":"B00OSTKZWM4",
	"name":"Professional WordPress Development",
	"Instructor":"Jony Ma",
	"img":"https://i.ibb.co/qrJCJpd/wordpress.png",	
	"price":9.99},
	{"key":"B00OSTKZWM5",
	"name":"Learn Veu JS",
	"Instructor":"Abul hill",
	"img":"https://i.ibb.co/513sLfY/vewjs.jpg",	
	"price":13.99},
	{"key":"B00OSTKZWM6",
	"name":"Complete HTML5",
	"Instructor":"Jammal Mia",
	"img":"https://i.ibb.co/xFKTf1K/html.png",	
	"price":9.99},
	{"key":"B00OSTKZWM7",
	"name":"Learn Advance CSS3",
	"Instructor":"Jammal Mia",
	"img":"https://i.ibb.co/R071GRV/csshero.png",	
	"price":9.99},
	{"key":"B00OSTKZWM8",
	"name":"Python Programming",
	"Instructor":"Kamal Hossien",
	"img":"https://i.ibb.co/Px6D3xh/Learn-Python.jpg",	
	"price":13.99},
	{"key":"B00OSTKZWM9",
	"name":"Complete Ruby on Rail Project",
	"Instructor":"Sojol Khan",
	"img":"https://i.ibb.co/sgV4X9Q/ruby-on-rails.jpg",	
	"price":9.99},
	{"key":"B00OSTKZWM10",
	"name":"Advance Internet Marketing",
	"Instructor":"Liton Kuman",
	"img":"https://i.ibb.co/0Gtymg0/Internet-Marketing.jpg",	
	"price":11.99},
	{"key":"B00OSTKZWM11",
	"name":"Complete Facebook Marketing",
	"Instructor":"Liton Kuman",
	"img":"https://i.ibb.co/850Lmb9/facebook-marketing.jpg",	
	"price":11.99},
	{"key":"B00OSTKZWM12",
	"name":"Learn MongoDB",
	"Instructor":"Abs Jony",
	"img":"https://i.ibb.co/Khv479B/mongoDB.jpg",	
	"price":9.99},
	{"key":"B00OSTKZWM13",
	"name":"Learn Magic of Photoshop",
	"Instructor":"Farjana Akter",
	"img":"https://i.ibb.co/rwZMqct/Photoshop.jpg",	
	"price":10.99},
	{"key":"B00OSTKZWM14",
	"name":"Complete PHP with Project",
	"Instructor":"Kamal Hossien",
	"img":"https://i.ibb.co/g3VxdNF/php.png",	
	"price":12.99},
	{"key":"B00OSTKZWM15",
	"name":"C++ Programming Hero",
	"Instructor":"Masudur Rahman",
	"img":"https://i.ibb.co/YWq0hLg/c.png",	
	"price":15.99}];
	
export default courseData;